version: "3.9"
services:
  app:
    image: prueba-tecnica-imagen
    container_name: prueba-tecnica-contenedor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

